### ISSUE TITLE
Crop after rotate

### ISSUE THREAD

**Issue by maeseee** [cgilles/digikam-photolayouteditor#1]
The crop tool does not rotate its area.

**Comment by maeseee** [comment]
For this issue the function boundingRect from AbstractItemInterface must be changed because it returns a QRectF Item. Basically this only includes a Position (x, y) and a Size (height, width) but the rotation also is needed.

**Comment by cgilles** [comment]
yes you are right. this function need to be patched...

**Comment by maeseee** [comment]
Oh, honestly I hoped for another answer. Anyway I like to share my idea with you before I start refactoring the code. Probably you come up with a much simpler solution for this problem as you are very experienced. 

The shape of the image is stored as a QPainterPath in the AbstractPhoto class. From this class I did not find a way to get all corners as QVector\<QPointF\> for my further calculations. I'm not happy with the solution to save the shape directly as a vector of points but I can't see another solution right now. This assumes that all images exactly have 4 corners. 

Another solution is to keep the solution from today and offer only 4 cutting rectangular. One on the top, one on the bottom, one on the right side and the last on the left side. So its somehow clear its only possible to cut horizontally and vertically. But be aware that this adds another 2 corners to each image.

**Comment by cgilles** [comment]
Following your first analysis, your proposal sound like simple and easy to apply. This is why i don't search an alternative.

Take a care : even if i review all codes, i don't write all this code myself. A student has work in 2010, 2011, 2012 to this project and write quickly this code. I only touch 35% of this code, the rest do not come from me.

I dropped and KDE dependencies, port to the plugin, add Raw support and start to use DK API everywhere. I pass all static analyzers and fix a lots of small problems... The code is enough mature and clean to be maintained safety.

Typically, the student never finalize this tool, and left the team to work to... Microsoft (:=)))...

For your second proposal, i don't have yet enough time currently to check if this solution is suitable or not.

Gilles

**Comment by cgilles** [comment]
In fact you want to find the closed rectangle including the whole QPainterPath of the image. Right ?

If yes, i'm sure that you can found this kind of code on the web as stackoverflow...

Gilles

**Comment by cgilles** [comment]
This method do not do the job ?

https://doc.qt.io/qt-5/qpainterpath.html#boundingRect

Gilles

**Comment by maeseee** [comment]
Thank you for your help. BoundingRect is the function currently used. Probably I did not explain the problem properly and we spoke not from the same thing. Attached you will find the way images are cropped in photoeditor and as a comparison libreoffice. 

![crop_libreoffice](https://user-images.githubusercontent.com/17683602/87244453-c4ade000-c43d-11ea-80c4-e6855444b79d.jpg)
![crop_photolayouts](https://user-images.githubusercontent.com/17683602/87244454-c5467680-c43d-11ea-89a0-3f285f2e0a23.jpg)

I also thought again about the problem and I think the most intuitive way could be achieved with the knowledge of all corner positions and not only the corners from the bounding rect. So the shape can be represented by a QPolygon. But as far as I know even a QPolygon does not return its corner positions.

**Comment by maeseee** [comment]
I found a nice solution to fix this issue. An upload will come soon.

**Comment by cgilles** [comment]
Marcel, Did you commit a fix ? If yes, i think we can CC the commit to a file report story automatically with github...

Gilles

**Comment by maeseee** [comment]
I pushed a fix to it. The magic is done by 00abc19ddf8b9dd22fc42f9ae73f65d9c0fd1cdd. I don't understand what you mean with CC to a file report story.

**Comment by cgilles** [comment]
With KDE git reprository, we can use post-commit hook macro included in commit message to push automatically a comment to a file report or to close file.

https://community.kde.org/Infrastructure/Git/Hooks

I think that a similar mechanism exists with github, as i seen this kind of rules in somes github project as Exiv2, libraw, QtAv, etc...

**Comment by maeseee** [comment]
Ah, I saw Maik using it and thought how he is doing that. Now I have a link and name for that. Thank you. I'll check it out.
