### ISSUE TITLE
Use delete key when active widget is on one or multiple layers to delete it

### ISSUE THREAD

**Issue by maeseee** [cgilles/digikam-photolayouteditor#2]
Select multiple layers one the left pane and press delete. Nothing happens. The layers must be deleted with right click and select delete.

**Comment by cgilles** [comment]
Marcel, you closed this file. It's a false positive report ?

Gilles

**Comment by maeseee** [comment]
Gilles, you were right. It was a false positive report. I got into this report because somehow I was confused from the problem described now. The fix is done with c499d240c36c27876e4a3c96d7a7226c53a39a5f, thats why it is closed.

**Comment by cgilles** [comment]
ok thanks

gilles
