### ISSUE TITLE
List of file formats for export is scrolled down

### ISSUE THREAD

**Issue by maeseee** [cgilles/digikam-photolayouteditor#4]
The list of file format in export first looks empty until scrolling down. 
See 
![missScrolling](https://user-images.githubusercontent.com/17683602/87873863-4618eb80-c9c5-11ea-8261-9bc388a0f417.jpg)

**Comment by maeseee** [comment]
I guess this is a qt problem. It can be fixed by choosing the last entry from the NameFilter. This doesn't make sense anyway. 
imageFileSaveDialog->selectNameFilter(list[list.size() - 1]);

Probably it works on other operating systems.

**Comment by cgilles** [comment]
Hum, i think it's the way to populate file format supported in the qt dialog. This can be customized.

Look how it's done in image editor or showfoto file save dialog.

Gilles

**Comment by maeseee** [comment]
Thank you for that tip. I quickly had a look to the other 2 products. They use a different kind of dialog. I try to use the same here.

**Comment by cgilles** [comment]
Look here:

https://invent.kde.org/graphics/digikam/-/blob/master/core/utilities/imageeditor/editor/editorwindow.cpp#L1656

https://invent.kde.org/graphics/digikam/-/blob/master/core/libs/widgets/files/dfiledialog.cpp

**Comment by maeseee** [comment]
Thank you for your help. In Digikam the option QFileDialog::DontUseNativeDialog is set on certain plattforms for the dialog in the custom DFileDialog class.
